version: "3.7"

services:
  mysql:
    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    hostname: "mysql"
    ports:
      - 3306:3306
    networks:
      - rede-docker
    volumes:
      - dados-bd:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: bd_docker
      MYSQL_USER: usr_docker
      MYSQL_PASSWORD: Teste123

  app:
    image: webdevops/php-apache:alpine-php7
    restart: always
    ports:
      - 80:80
    networks:
      - rede-docker
    working_dir: /app
    volumes:
      - ./index.php:/app/index.php
    depends_on:
      - mysql

volumes:
  dados-bd:

networks:
  rede-docker: